### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by gokaygurcan**
fixes a typo.

doesnotcompute

## Description

see above.

## Motivation and Context

it's not solving anything actually. i'm not sure if anyone needs this change. but yea, it fixes a typo.

## How Has This Been Tested?

by just reading the README.md file maybe? idk. 

## Screenshots (if appropriate):
yes, sure, why not? there you go:
screen shot 2018-03-22 at 21 01 16

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] none of the above

## Author's Checklist:

- [ ] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.
- [x] i.. i don't know. i guess it kind of covers the last item. or maybe not. 

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Nice!

**Comment by gokaygurcan** [comment]
That's a no then. 
Thanks!

**Comment by robertleeplummerjr** [comment]
Sorry, I thought I hit merge.  PR's are welcome, as well as imperfection.

**Comment by gokaygurcan** [comment]
Ah, I was so sad after I prepared this lovely PR report saw that it was closed :P
Thanks a lot! 

BTW: I'm a huge fan of this work, will definitely use it in one of my next projects.

**Comment by robertleeplummerjr** [comment]
Sorry for the sadness, I hope I've turned everything around.  I look forward to more contributions in the future!

>BTW: I'm a huge fan of this work, will definitely use it in one of my next projects.

Ty!  That means a lot!

**Pull request merged**
