### PR TITLE
svg network rendering 2

### PR DESCRIPTION
**Pull request by geokontop**
Should be considered as continuation of pull request #309

- [X] function **toSVG** filename **to-svg** in src/utilities
- [X] argument **network** instead of **size**
- [X] function called as brain.utilities.toSVG{network,options) 
- [X] verbosity reduced
- [X] dist files, browser.js, browser.min.js
- [X] fast-xml-parser as devDependency, testing valid xml
- [X] semicolons
- [x] example implementation clientside 
- [x] documentation

### CODE REVIEW

**Comment by geokontop** [comment]
@robertleeplummerjr may I have a review?

**Comment by geokontop** [comment]
Invisible.

**Comment by robertleeplummerjr** [comment]
This is a worthwhile PR, I've just been traveling with family for the past week, and I appologize for my neglect.  I promise to review asap, likely today.

**Comment by gkontop** [comment]
I am sorry. I didn't mean to rush you. Nice to know it's going on.

**Review by robertleeplummerjr — APPROVED** [review]
Really nice job.  Ty for your hard work!

**Pull request merged**
