### PR TITLE
Examples in README expanded with cat dog classifier link and short classifier code example 

### PR DESCRIPTION
**Pull request by Nelias**
A GIF or MEME to give some spice of the internet

## Description

Added another live example of Brain.js in action

## Motivation and Context

This is the result of a discussion here: https://github.com/BrainJS/brain.js-examples/pull/1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [x] My code passes current tests and adds new tests where possible.
- [x] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [x] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by Nelias** [comment]
@robertleeplummerjr any comments on this one? It still has not been merged since May.

**Comment by robertleeplummerjr** [comment]
I'll merge it this week, sorry for the long delay.

**Comment by robertleeplummerjr** [comment]
Please open this PR in https://github.com/BrainJS/brain.js-examples.

Thank you.

**Comment by Nelias** [comment]
@robertleeplummerjr I reopened the PR in the examples repository: https://github.com/BrainJS/brain.js-examples/pull/1

**Pull request closed without merging**
