### PR TITLE
Refine and vectorize logo

### PR DESCRIPTION
**Pull request by janwirth**
See #20

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Fantastic!

**Comment by robertleeplummerjr** [comment]
It shows up now as a link.  Any way to resolve to show the world that beauty?

**Comment by wagenaartje** [comment]
I think it needs to be hosted somewhere else.

https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

**Comment by janwirth** [comment]
Oh - I will open a PR to the gh-pages branch. :) Gimme a second.

**Pull request merged**
