### PR TITLE
Add react-native exmaples of working with brain.js

### PR DESCRIPTION
**Pull request by jusso-dev**
brain.js React Native Example

A GIF or MEME to give some spice of the internet

## Description

Adding example react native project that works with offline trained model.

## Motivation and Context

Request for examples below.

[issue](https://github.com/BrainJS/brain.js/issues/171)

## How Has This Been Tested?

N/A these changes are not changing the library.

## Screenshots (if appropriate):

example-image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [ ] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ X] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
What if we opened a new project under BrainJS foundation, and merged this there so this can be reused and as well used as a platform for other react components?

**Comment by jusso-dev** [comment]
Yeah that would be fine

**Comment by robertleeplummerjr** [comment]
To hasten the acceptance: https://github.com/BrainJS/ReactNative

While this is fantastic work, one of the items we'd really like to aim for is neural networks that are simple enough for anyone to use, including kids.  That being said, would it be possible to get a rated G version of the classifier?


bart

**Comment by jusso-dev** [comment]
Understood, I'll re-train and republish to the newly created ReactNative area of the repo. It's a public holiday here in Canberra Australia so later today I'll push the changes.

**Comment by Sam-Hoult** [comment]
Hey, if you wanted the usual examples of training for colours whether it's light or dark. I converted the material-ui colors to an input object: https://github.com/Sam-Hoult/BrainJS-material-ui-color-picker/blob/master/materialui-color-data.js if that helps in anyway

Parsed from: http://www.material-ui.com/#/customization/colors

**Comment by jusso-dev** [comment]
Thanks, I've just re-trained it using more clean lyrics. The examples are sitting awaiting approval under the ReactNative branch on the brain js project.

**Comment by robertleeplummerjr** [comment]
Ty for the hard work on this!  It is now handled here: https://github.com/BrainJS/BrainJSReactNative

**Pull request closed without merging**
