### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Comment by mubaidr** [comment]
We are using actions/setup-node@v2-beta to setup node which does support caching project dependencies. Although we could use version upgrade. 
Can you check on that?

https://github.com/BrainJS/brain.js/pull/734/files#diff-e98936aa52a6dd7416e4296e9628456227d834f7245967383fd9ff80fd985dadL18

**Comment by oscard0m** [comment]
> We are using actions/setup-node@v2-beta to setup node which does support caching project dependencies. Although we could use version upgrade. Can you check on that?
> 
> https://github.com/BrainJS/brain.js/pull/734/files#diff-e98936aa52a6dd7416e4296e9628456227d834f7245967383fd9ff80fd985dadL18

Sure! let me take a look into it

**Comment by oscard0m** [comment]
Since I deleted my fork I had to regenerate the fork, branch and PR. Please, check the changes here: https://github.com/BrainJS/brain.js/pull/743

**Comment by robertleeplummerjr** [comment]
Since this is as old as it is, let's go ahead and nuke it.  Please feel free to reopen.

**Pull request closed without merging**
