### PR TITLE
fix: Fix unit tests

### PR DESCRIPTION
**Pull request by baradm100**
## Description
Fix a few things related to the unit tests (and even some) that always were failing beforehand:
* Bad typescript config - was not letting us run the unit tests on Node versions older than 14.x
* Changed modifier validation
* Fixing assertion for the following tests:
  * `uses compare2D when width > 1`
  * `converts Textures to Arrays of numbers`

## Motivation and Context
We have unit tests to check the code but currently, we have a few unit tests that are failing, fixing the problematic tests will allow us to have more trust in our unit tests

## How Has This Been Tested?
Run:
```bash
npm test
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:
- [X] My code focuses on the main motivation and avoids scope creep.
- [X] My code passes current tests and adds new tests where possible.
- [X] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [X] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by baradm100** [comment]
If you like I can revert the `package-lock.json` file 😁

**Comment by baradm100** [comment]
Please don't merge/review yet, I want to see if I can get the build to pass

**Comment by baradm100** [comment]
Hmm, so I fixed a few tests + the typescript config.
Now the only test that failed are the ones who train and run a model (beforehand the tests were failing due to not recognizing ES features like nullish coalescing)

**Comment by baradm100** [comment]
Hi team!
The PR is ready to be reviewed!!
I've fixed all the tests that I could...

**Comment by mubaidr** [comment]
Awesome work! 👍🏼

**Pull request merged**
