### PR TITLE
Convert /activation to typescript

### PR DESCRIPTION
**Pull request by harshkhandeparkar**
**Convert /activation to ts and configure jest properly to preprocess ts files.**

## Description
- Convert each of the files in `/activation` to typscript.
- Used the `ts-jest/presets/js-with-babel` from `ts-jest` for jest config.
- Removed any transforms in jest config and used preset instead.
- I had to touch the jest files or else the tests wouldn't pass.

## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/551)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] ¯\\\_(ツ)\_/¯

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [x] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by harshkhandeparkar** [comment]
Sorry for using master branch. Realised that 5 mins ago :stuck_out_tongue:

**Comment by harshkhandeparkar** [comment]
I changed everything from activation/ since they were completely connected. I removed default exports so I had to change index.js

Since I changed index, I had to change the others.

**Comment by harshkhandeparkar** [comment]
I'll remove the dist :)

**Review by mubaidr — APPROVED** [review]

**Comment by harshkhandeparkar** [comment]
Ty :). I'll convert more files as soon as I get time. I have a bit of experience in converting whole projects to ts :joy:

**Comment by mubaidr** [comment]
Good work, Thanks you! 👍

**Comment by robertleeplummerjr** [comment]
Awesome work guys!

**Pull request merged**
