### PR TITLE
resolves svg issue 384

### PR DESCRIPTION
**Pull request by geokontop**
A GIF or MEME to give some spice of the internet

## Description
The problem is that when the network is created from a json object it keeps the network's sizes info in the attribute "sizes". While when created from the constructor the sizes attribute is null. In that case the sizes' info is kept in the attributes "inputSize", "outputSize" and "hiddenLayers". 

## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/###)

## How Has This Been Tested?
Tested in the browser for networks created from the constructor and networks created with fromJSON(json) method

## Types of changes
 I had to add a line of code in  to-svg.js. 
if(!size) size = network.sizes;
So that both cases are checked.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by geokontop** [comment]
resolves issue 384

**Comment by robertleeplummerjr** [comment]
Ty for the PR!  There seems to be a lot of cache files added with this PR.  Any chance of having them removed?

**Comment by geokontop** [comment]
I don't know why that happened. It looks like babel's compilation recreates all the files, so they appear to be altered. I will repeat the procedure tomorrow with a new pr. Have a nice day,

**Comment by robertleeplummerjr** [comment]
You rock Georgios.

**Pull request closed without merging**
