### PR TITLE
Join Slack Community: Briim - Machine Learning in JavaScript

### PR DESCRIPTION
**Pull request by rwieruch**
Hello @robertleeplummerjr  and everyone else! I have seen that you don't have any Slack Group for your library. That's why I want to propose the [BRIIM](https://bri.im/) community as [Slack Community](https://slack.bri.im/) for your library. I believe it would help people tons to discuss and learn from each other in an interactive chat.

BRIIM, the Machine Learning in JS movement, tries to gather all developers using ML and ML related libraries in JS in one community. I believe it is great to learn from each other when using one library, but also to explore other libraries in the ML in JS ecosystem. So far, every library is its own little community. However, in order to make ML in JS a larger topic this year, I try to bring together all developers/communities with this movement. 

In the next days, I want to propose the community [to other ML and ML related libraries](https://bri.im/libraries) too. It would be great to have you with us in order to strengthen the ML in JS movement in 2018 :) If you are more interested in my doings, please checkout [this blog post](https://www.robinwieruch.de/machine-learning-javascript-web-developers/). I hope the article shows that I mean it serious with BRIIM :) Thanks for considering to participate! If it doesn't work out, you can always leave the Slack Community. **But I hope to bootstrap this community to make ML in JS happen in 2018.** 🚀

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
We already have a slack channel [here](https://brain-js.slack.com) is there any way to link them?  It is in-tern, linked to gitter.

**Comment by rwieruch** [comment]
Ah okay. I am too late :) Not sure if there is a way to link them. However, maybe people still join the broader ML in JS community :)

**Comment by robertleeplummerjr** [comment]
No fear, an easy migration as we're not really using it. It is simply bound to gitter.

**Comment by robertleeplummerjr** [comment]
Can I get any other :+1:'s?

**Comment by benedictchen** [comment]
Can I get an invite to this slack channel? TheBenedictChen@Gmail.com

**Comment by rwieruch** [comment]
It is possible by self-invitation: https://slack.bri.im @benedictchen

**Comment by robertleeplummerjr** [comment]
What if we:
1. linked existing gitter chat to this new location
2. put the description in gitter if they want more insight, they could use the briim slack room
3. deprecate the existing slack room, unlinking it from gitter, and simply put description that it has been moved

This unifies efforts, and consolidates chat.

**Comment by freddyC** [comment]
5esmt9i

**Comment by robertleeplummerjr** [comment]
Merging now, can clean it up later.

**Pull request merged**
