### PR TITLE
Fix wrong log callback type

### PR DESCRIPTION
**Pull request by colus001**
Fix wrong log callback type on trainingOptions

cat
## Description

Only tiny fix to avoid confusion on log callback options

## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/446)
Kind of related

## How Has This Been Tested?

No test required

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [ ] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [x] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by mubaidr** [comment]
I think the trainingLogCallback and trianingCallback has same interface. Both returns iterations and error. So why a different type?

**Comment by colus001** [comment]
No it doesn't. 

logCallback returns `string`
callback returns `state`

```
const trainingOptions: INeuralNetworkTrainingOptions = {
  ...
  callback: console.log,
  ...
}
```

Will print.

```
{ iterations: 40, error: 0.1505548765650579 }
{ iterations: 41, error: 0.07967034997254249 }
```

By the way, 

```
const trainingOptions: INeuralNetworkTrainingOptions = {
  ...
  log: console.log,
  ...
}
```

will print out as below returning `string` not `INeuralNetworkState`

```
iterations: 30, training error: 0.24721950121220654
iterations: 40, training error: 0.1505548765650579
```

I don't think logCallback is actually necessary but at least type should be fixed.
It took me a while to find what's wrong here, since type was both State

**Review by mubaidr — APPROVED** [review]

**Comment by mubaidr** [comment]
Sounds good, but it would be even better if we can make arguments same for both. So that `state` is passed to user provided function not the string. 

Can you please update so that:
- If `log` is true, then use console log to print string message
- If `log` is function (provided by user) then pass state to the function

Changes required here: https://github.com/BrainJS/brain.js/blob/master/src/neural-network.js#L446

**Comment by colus001** [comment]
@mubaidr I reverted the type changes, and fixed log related codes. any comment?

**Review by mubaidr — APPROVED** [review]

**Comment by mubaidr** [comment]
Just  a minor step, there is a redundant interface now: : https://github.com/BrainJS/brain.js/blob/279befba202558f1e7e18af30408880e13404e1a/src/index.d.ts#L89

**Comment by mubaidr** [comment]
Updated tests are failing too. Please have a look. 
https://travis-ci.org/BrainJS/brain.js/jobs/591940249#L277
https://travis-ci.org/BrainJS/brain.js/jobs/591940249#L296

**Comment by mubaidr** [comment]
Everything except the above two changes required looks good, thanks for your patience and contribution. 👍

**Comment by colus001** [comment]
```
$ npm run test ./__tests__/neural-network/json.js

> brain.js@2.0.0-alpha.9 test /Users/alma/Development/brain.js
> jest --env=node "./__tests__/neural-network/json.js"

 PASS  __tests__/neural-network/json.js

Test Suites: 1 passed, 1 total
Tests:       71 passed, 71 total
Snapshots:   0 total
Time:        0.698s, estimated 1s
Ran all test suites matching /.\/__tests__\/neural-network\/json.js/i.
```

`index.d.ts` no longer exists in this PR 😄

**Review by mubaidr — APPROVED** [review]

**Comment by mubaidr** [comment]
Thanks again! Looking forward to more contributions!

**Pull request merged**
