### PR TITLE
Typescript migrate

### PR DESCRIPTION
**Pull request by vorticalbox**
# Type all the things

This PR is to help with the conversion to typescript.

As i have never worked on this code base before, I know very little about the interfaces and am creating them based on the context of the file. these will need to be revisited. 

## Motivation and Context

I don't know much about maths or neural networks but typescript I know and I love brain.js

## How Has This Been Tested?
XD not even a little bit tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [ ] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
- [ ] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by vorticalbox** [comment]
@mubaidr merged in master on my fork and did a PR, hope this is right :) still not great with git

**Comment by mubaidr** [comment]
Looks good now. Looking forward! 👍

**Comment by robertleeplummerjr** [comment]
How is this looking?

**Comment by vorticalbox** [comment]
It's going out, I'm working 40 hours a week so I'm doing little bits when my time frees up.

**Comment by robertleeplummerjr** [comment]
>I'm working 40 hours a week so I'm doing little bits when my time frees up.

Same here, ty for your hard work.

**Comment by l0gicgates** [comment]
I can help with this too. We are actually currently doing a project at work migrating AngularJS to Angular (TypeScript)

**Comment by mubaidr** [comment]
@l0gicgates please start here: https://github.com/BrainJS/brain.js/issues/551

**Comment by vorticalbox** [comment]
@l0gicgates feel fre to branch from master and then copy my changes over. I am super busy at work and have yet to find any time to work on this :(

**Comment by l0gicgates** [comment]
@mubaidr @vorticalbox  Ok perfect. I will be pushing some of the converted files in a few days. 
How are we handling doing `npm install` and `npm rebuild` with partially converted files (legacy JS vs newly converted TypeScript)? 
I saw we have the `build` script but I am not sure if it is actually running through with the TS files

**Comment by mubaidr** [comment]
@l0gicgates Please refer to issue for more information: https://github.com/BrainJS/brain.js/issues/551

Build scripts have been updated and should work. 


Closing this until @vorticalbox take over this again.

**Pull request closed without merging**
