### PR TITLE
Attempted Fix for Streaming

### PR DESCRIPTION
**Pull request by binarybehemoth**
This is my attempted fix for the issue raised below:
https://github.com/BrainJS/brain.js/issues/239

[partial fix for stream.zip](https://github.com/BrainJS/brain.js/files/2206320/partial.fix.for.stream.zip)

...first time making a pull request...how do I show the code changes directly?

### CODE REVIEW

**Comment by mubaidr** [comment]
Thanks. 

You need to choose your branch for pull request. Currently you have created pull request to fetch changes from master branch to develop branch. 

Don't worry, nothing major. 

- Fork this repo
- Clone to your PC
- Update code files where required
- Push commit
- Create pull request in brain.js develop branch
- Choose your master branch as source. 
- Submit
- Profit!

**Comment by binarybehemoth** [comment]
ok... 

This is going to take some time but the time is rather late here. I will explore how to do this tomorrow.

I presume when I Submit, my files won't replace those in the public repository directly. As I said, I fear the changes need some checking to ensure compatibility with other users.

**Comment by mubaidr** [comment]
Thanks and no worries, it wont update automatically. We will review changes together and then merge them.

**Comment by binarybehemoth** [comment]
I changed the files and clicked 'Commit to develop' in GitHub Desktop. Now what? Is it done?

**Comment by mubaidr** [comment]
You are halfway there! Just: 

- Visit Github in your browser (brain.js)
- Create pull request in brain.js develop branch by clicking the pull-request link
- Choose your master branch as source.
- Submit
- Profit!

UPDATE:
I have done it for you, you can track and participate in discussion here: https://github.com/BrainJS/brain.js/pull/243

Also closing this one as it is not required now.

**Pull request closed without merging**
