### PR TITLE
Fixing bad function creation inside loop neural-network-gpu

### PR DESCRIPTION
**Pull request by gabrielfreire**
Just moved the callback outside the loop

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Is the lock file needed right now?

**Comment by gabrielfreire** [comment]
No, sorry... it would be good to put it inside .gitignore

**Comment by robertleeplummerjr** [comment]
mind adding in this pr?

**Comment by gabrielfreire** [comment]
Done

**Comment by abhisheksoni27** [comment]
"Bad function creation" ? Really?

**Comment by gabrielfreire** [comment]
sorry, not bad the way you're thinking maybe. 
bad place**

**Comment by robertleeplummerjr** [comment]
Can you leave the map files out as well?

**Comment by gabrielfreire** [comment]
i deleted them and put inside .gitignore

**Comment by gabrielfreire** [comment]
i deleted them and put inside .gitignore

**Comment by robertleeplummerjr** [comment]
@gabrielfreire can you read this https://github.com/harthur-org/brain.js/wiki/Roadmap to get aquanted with where we are going next?  I'm loving what I'm seeing here.

**Comment by gabrielfreire** [comment]
Done, thats great... can you show me how you are making your tests?

**Comment by robertleeplummerjr** [comment]
outdated.

**Pull request closed without merging**
