### PR TITLE
__tests__/recurrent/end-to-end.js to ts

### PR DESCRIPTION
**Pull request by dhairyagada**
A GIF or MEME to give some spice of the internet

## Description

Converted https://github.com/BrainJS/brain.js/blob/master/__tests__/recurrent/end-to-end.js to ts
## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/551)

## How Has This Been Tested?

It is a test file
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [x] My code passes current tests and adds new tests where possible.
- [x] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by mubaidr** [comment]
Please merge latest commit from `master`

**Comment by dhairyagada** [comment]
Hi @mubaidr , I have merged recent master commits, can you please verify ?

**Comment by mubaidr** [comment]
You have merged `master` of `dhairyagada`, please pull `master` of `origin` i.e. github.com/BrainJS/brain.js

**Comment by dhairyagada** [comment]
Hey @mubaidr ,  I am trying to fetch and merge the original repository `https://github.com/BrainJS/brain.js.git`, but it is showing me that my repo is already up to date. Can you guide me on how do I merge it?

What I did earlier was - 

`git remote add upstream https://github.com/BrainJS/brain.js.git`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`

**Comment by mubaidr** [comment]
NVM, there is no conflict with the `master` branch.

**Comment by JCMais** [comment]
this PR added eslint errors to the repo (they are fixable by running with the --fix flag).

**Comment by mubaidr** [comment]
@JCMais Fixed the errors. 👍🏼

**Pull request merged**
