### PR TITLE
Added clean script

### PR DESCRIPTION
**Pull request by mubaidr**
https://github.com/BrainJS/brain.js/issues/172

### CODE REVIEW

**Review by freddyC — CHANGES_REQUESTED** [review]
Hi @mubaidr 

Thanks so much for putting this together.

One of the appealing things about `brain.js` is how few dependencies it has.  I think it would be better to do the same work just in a script and not add in a new dependency.   I think the `packages.json` can just run the script with node (like this) i.e. `"clean": "node rimraf.js"`

I recently did this very thing in a different project and here is what I came up with:
```
'use strict';

var fs = require('fs');

var node_modules = './node_modules';

function deleteFolderRecursive (path) {
  if( fs.existsSync(path) ) {
    fs.readdirSync(path).forEach(function(file,index){
      var curPath = path + "/" + file;
      if(fs.lstatSync(curPath).isDirectory()) { // recurse
        deleteFolderRecursive(curPath);
      } else { // delete file
        fs.unlinkSync(curPath);
      }
    });
    fs.rmdirSync(path);
  }
};

deleteFolderRecursive(node_modules);
```

I was only using it on a mac so I have only tested it in iOS but I think it should be platform independent.  Do you mind adding a script to do this work and getting rid of the new dependency?

Thank you again good sir for stepping in and adding this, and sorry if it seems hyper critical.  One of the big focuses for brain is simplicity and one way to help that is to reduce the number of dependencies.

**Comment by robertleeplummerjr** [comment]
One could reason that since we're removing one directory the simplest means would be `rm -rf node_modules` or `rmdir node_modules /s`.

Not to sound dogmatic, but is there a reason specifically that a clean script is needed?  It feels a bit like solving something that has already been solved.

**Comment by robertleeplummerjr** [comment]
But I gotta say, I love the speed at which this was added. That enthusiasm is especially what any successful project needs!

**Comment by freddyC** [comment]
Yeah it doesn't have to be a script, I was just thinking something that is cross platform, but I am open to either approach.  Mainly I think there is benefit in keeping dependencies low.

**Comment by Macil** [comment]
It is only a devDependency: if someone runs `npm install brain.js`, then rimraf doesn't get downloaded and used. (Also, rimraf happens to already be a transitive dependency of some of the other current devDependencies of brain.js (ie. babel-cli -> chokidar -> fsevents -> node-pre-gyp -> rimraf), so adding it to package.json doesn't currently result in anything more being installed in dev. It definitely should be listed in package.json if it gets used directly by brain.js though.)

**Comment by robertleeplummerjr** [comment]
I think @AgentME raises a good point, we already use it.  @freddyC, your thoughts?

**Comment by freddyC** [comment]
@AgentME Great point, I totally didn't realize it was just a dev dependancy.  I also didn't realize it is already in the dependency tree.  With that being pointed out to me I am totally on board.  Sorry I didn't realize that before hand.

@robertleeplummerjr  I changed my review to be fine with this.

**Review by freddyC — APPROVED** [review]

**Comment by freddyC** [comment]
@mubaidr Also thank you again for your pr, sorry I was wrong in my original review.  Great work man.

**Comment by mubaidr** [comment]
@freddyC @robertleeplummerjr @AgentME Sorry, I have not been able to comment on this, probably would have solved this issue earlier. But thanks. :) Its just a very very minor contribution :p

**Pull request merged**
