### PR TITLE
fix: toJSON & toFunction for NeuralNetworkGPU class

### LINKED ISSUE #310: toJSON not working on NeuralNetworkGPU in Chrome 70
## *What* is wrong?
Can't call toJSON() on NeuralNetworkGPU

## *Where* does it happen?
Windows10 and MacOs Mojave in Chrome 70 on GTX1060 or Intel iGPU

## *How* do we replicate the issue?
- Train a NNGPU in your browser.
- console.log(net.run(bla)) -> successfull output
- net.toJSON() -> `Cannot read property '0' of undefined`
It happens here:
https://github.com/BrainJS/brain.js/blob/78f369f4a624ded30e9b828950ad828c6fb83953/src/neural-network.js#L923

I think it tries to access index 0 of the [1] layer. But as you can see there is nothing to access.

```
JSON.stringify(this.weights) =>
"[null,{"texture":{},"size":[736,368],"dimensions":[736,368,1],"output":[736,368],"webGl":{},"kernel":null,"type":"NumberTexture"},{"texture":{},"size":[368,230],"dimensions":[368,230,1],"output":[368,230],"webGl":{},"kernel":null,"type":"NumberTexture"}]"
```

## *How* important is this (1-5)?

5 because i can't save my training data at all :( 
## Expected behavior (i.e. solution)

Output me the json so i can save the training

## Other Comments
I'm very new to NN

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
fixes #310 and adds tests

A GIF or MEME to give some spice of the internet

## Description
I woke up in a haze on Sunday morning to this issue, and at first sight thought "oh yea, that was not completed", and then with nearly this exact expression:

I believed I could resolve it fairly easily.  AND because this issue is the backbone of `.toFunction()` is resolved that issue as well.  I tested in both cpu mode for gpu.js and gpu mode.

Great job in finding, suggesting, and motivating.

## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/310)

## How Has This Been Tested?
Direct unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [x] My code passes current tests and adds new tests where possible.
- [x] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [x] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
@koriwi, may I have a review?

**Comment by robertleeplummerjr** [comment]
Going to go ahead and merge PR to keep things timely.

**Comment by koriwi** [comment]
Sorry. The notification was burried under my work notifications.

**Comment by robertleeplummerjr** [comment]
But, does it work for you?

**Comment by koriwi** [comment]
I wanted to test yesterday. But my docker-mongodb crashed because of apfs. Whole DB unrepairable gone. Installed Manjaro today and will test it in a few hours

**Comment by robertleeplummerjr** [comment]
ty sir.  Sorry to hear that happened.

**Comment by koriwi** [comment]
works. Thank you sir :)

**Comment by robertleeplummerjr** [comment]
Great to hear!

**Pull request merged**
