### PR TITLE
Abstract a base class from NeuralNetwork and RNN

### PR DESCRIPTION
**Pull request by bdistin**
A GIF or MEME to give some spice of the internet

## Description

This makes training/asyncTraining consistent across all classes, allowing you to trainAsync on RNN based classes where you couldn't before.

## Motivation and Context

It adds asyncTraining and by extension a consistent API to all classes in a DRY way.

[issue](https://github.com/BrainJS/brain.js/issues/356)

## How Has This Been Tested?

I had a friend with access to a linux vps run the unit tests.

I develop and host on windows/windows server. Seperate issue is the way the some scripts are written in package.json don't work on windows machiens. I, however, did not scope creep to change the scripts to be OS independent.

In theory it shouldn't affect other areas of code. The two training methods used to be the same before async training was added, and what was changed in NeuralNetwork should be effectively the same as what was repeated in RNN.

## Screenshots (if appropriate):
test log

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [ ] My code passes current tests and adds new tests where possible.
  - This doesn't add any new tests, and passes all tests __currently passing on the repo__ (one test has not passed in a while). Techincally if trianAsync is already being tested on NeuralNetwork, that test should provide coverage for all other classes since this doesn't really add new code, but reorganizes existing code so that it's usable on all classes.
- [x] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.
  - I am not sure the documentation needs updating as the documentation alluded this was already possible.
## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

**Comment by mubaidr** [comment]
Looks good to me! nice work!

@robertleeplummerjr please

**Comment by bdistin** [comment]
Uhh, hold off on merging, I seem to have found some bugs  ~~related to this pr~~ when attempting some usecases. Tracking them down. I will give further updates when this will be ready.

update:

Actually, I am not sure if my issue is related to this pr or my usage. I was training LSTM on `{ input, output}` format data. Obviously, that object doesn't have a length, so when trying to backpropagate the input, i is undefined: img

**Comment by bdistin** [comment]
ok, yes, that was the issue. I have now fixed it within the scope of this pr. However, in a future change, it may be a good idea to combine the two data mutation methods under one name. That is if my assumption is correct and they are never applicable together.

**Comment by mubaidr** [comment]
@robertleeplummerjr please, your input is required

**Comment by robertleeplummerjr** [comment]
I think what we need to do is fix develop, merging changes into there from master first, and then this needs to be merged into develop, and applied as well to the `Recurrent` and `FeedForward` classes. Then we can merge it in, and drop x4 times the code with this.  What do you guys think?

**Comment by bdistin** [comment]
While I don't exactly follow the git-fu you are suggesting, haven't looked at this codebase in nearly 4 months, and am more time-strapped than ever; you are free to use this code or not and run with that other idea to abstract the other 2 classes too.

If I have some time I might try and apply it to those 4 classes on your development branch (if that's basically what you are suggesting?), but I wouldn't count on my having time to do that.

I don't mean to pr and ditch, but I had assumed it would have been reviewed long before now.

**Comment by mubaidr** [comment]
I believe code base is ready to accept these changes. @bdistin Can you please finalize? 🍭

**Comment by bdotsamir** [comment]
Hi everyone, quick update bump?
I'm not sure what's happening here but from what I can assume all NN classes (LSTM, RNN, etc) will have async training. The code seems to be ready, but that was back in April.

**Comment by robertleeplummerjr** [comment]
>Hi everyone, quick update bump?

I'm working on a bug in GPU.js for brain.js at the moment, I think we just need someone to commandeer this.  I don't think there is a great deal of work, but more just someone owning it, and who has the time.

**Pull request closed without merging**
